# Generated by Django 6.0 on 2025-12-20 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('customers', '0002_alter_customer_created_at_alter_customer_deleted_at_and_more'),
        ('drivers', '0002_alter_driverpayment_created_at_and_more'),
        ('vehicles', '0002_alter_vehicle_category_alter_vehicle_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка о мягком удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Время когда запись была помечена как удаленная', null=True, verbose_name='Дата удаления')),
                ('trip_date', models.DateField(help_text='Дата выполнения поездки', verbose_name='Дата поездки')),
                ('departure_time', models.TimeField(help_text='Время начала поездки', verbose_name='Время отправления')),
                ('departure_location', models.CharField(help_text='Адрес или название точки отправления', max_length=255, verbose_name='Место отправления')),
                ('arrival_location', models.CharField(help_text='Адрес или название пункта назначения', max_length=255, verbose_name='Место прибытия')),
                ('passenger_count', models.IntegerField(help_text='Фактическое количество пассажиров', verbose_name='Количество пассажиров')),
                ('planned_amount', models.DecimalField(decimal_places=2, help_text='Запланированная стоимость поездки (в рублях)', max_digits=10, verbose_name='Плановая сумма')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Итоговая стоимость после выполнения (в рублях)', max_digits=10, null=True, verbose_name='Фактическая сумма')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('PAID', 'Оплачено'), ('PARTIAL', 'Частично оплачено')], default='PENDING', help_text='Текущий статус оплаты поездки', max_length=50, verbose_name='Статус оплаты')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланирована'), ('IN_PROGRESS', 'В пути'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='PLANNED', help_text='Текущий статус выполнения поездки', max_length=50, verbose_name='Статус поездки')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки о поездке', verbose_name='Примечания')),
                ('booking', models.ForeignKey(blank=True, help_text='Связанное бронирование (если есть)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='bookings.booking', verbose_name='Бронирование')),
                ('customer', models.ForeignKey(help_text='Клиент, для которого выполняется поездка', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='customers.customer', verbose_name='Клиент')),
                ('driver', models.ForeignKey(help_text='Водитель, выполняющий поездку', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='drivers.driverprofile', verbose_name='Водитель')),
                ('vehicle', models.ForeignKey(help_text='Транспорт, используемый для поездки', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
                'ordering': ['-trip_date', '-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка о мягком удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Время когда запись была помечена как удаленная', null=True, verbose_name='Дата удаления')),
                ('location', models.CharField(help_text='Адрес или название остановки', max_length=255, verbose_name='Местоположение')),
                ('stop_order', models.IntegerField(help_text='Порядок остановки в маршруте', verbose_name='Порядковый номер')),
                ('trip', models.ForeignKey(help_text='Поездка, к которой относится остановка', on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip', verbose_name='Поездка')),
            ],
            options={
                'verbose_name': 'Остановка',
                'verbose_name_plural': 'Остановки',
                'ordering': ['stop_order'],
            },
        ),
    ]
