# Generated by Django 6.0 on 2025-12-20 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contact_person_name', models.CharField(help_text='ФИО контактного лица', max_length=255, verbose_name='Контактное лицо')),
                ('organization_name', models.CharField(blank=True, help_text='Название компании (если клиент - организация)', max_length=255, verbose_name='Название организации')),
                ('phone', models.CharField(help_text='Контактный номер телефона', max_length=25, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='Адрес электронной почты', max_length=254, verbose_name='Email')),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Физическое лицо'), ('ORGANIZATION', 'Организация')], help_text='Физическое лицо или организация', max_length=50, verbose_name='Тип клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
