# Generated by Django 6.0 on 2025-12-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_created_at_alter_customer_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Контактный номер телефона', max_length=25, unique=True, verbose_name='Телефон'),
        ),
    ]
