# Generated by Django 6.0 on 2025-12-20 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.CharField(help_text='Марка транспортного средства (например, Mercedes)', max_length=50, verbose_name='Марка')),
                ('model', models.CharField(help_text='Модель транспортного средства (например, Sprinter)', max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(help_text='Год производства транспортного средства', verbose_name='Год выпуска')),
                ('license_plate', models.CharField(help_text='Регистрационный номер транспортного средства', max_length=20, unique=True, verbose_name='Гос. номер')),
                ('capacity', models.IntegerField(help_text='Количество пассажирских мест', verbose_name='Вместимость')),
                ('category', models.CharField(choices=[('BUS', 'Автобус'), ('MINIBUS', 'Микроавтобус'), ('VAN', 'Фургон')], help_text='Тип транспортного средства', max_length=50, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, help_text='Доступен ли транспорт для использования', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
    ]
