# Generated by Django 6.0 on 2025-12-20 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(help_text='Контактный номер телефона водителя', max_length=25, verbose_name='Телефон')),
                ('license_number', models.CharField(help_text='Уникальный номер ВУ', max_length=25, unique=True, verbose_name='Номер водительского удостоверения')),
                ('license_category', models.CharField(help_text='Категория водительского удостоверения (например, D, D1)', max_length=25, verbose_name='Категория ВУ')),
                ('hire_date', models.DateField(help_text='Дата приема на работу', verbose_name='Дата найма')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('INACTIVE', 'Неактивен'), ('ON_VACATION', 'В отпуске')], default='ACTIVE', help_text='Текущий статус водителя', max_length=50, verbose_name='Статус')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Оплата за один рабочий день (в рублях)', max_digits=10, verbose_name='Дневная ставка')),
                ('user', models.OneToOneField(help_text='Связанный аккаунт пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль водителя',
                'verbose_name_plural': 'Профили водителей',
            },
        ),
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateField(help_text='Дата фактической выплаты', verbose_name='Дата выплаты')),
                ('period_start', models.DateField(help_text='Дата начала расчетного периода', verbose_name='Начало периода')),
                ('period_end', models.DateField(help_text='Дата окончания расчетного периода', verbose_name='Конец периода')),
                ('days_worked', models.IntegerField(blank=True, editable=False, help_text='Автоматически вычисляется на основе периода', null=True, verbose_name='Отработано дней')),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Автоматически вычисляется: дни × ставка', max_digits=10, null=True, verbose_name='Базовая сумма')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, help_text='Дополнительная премия (в рублях)', max_digits=10, verbose_name='Сумма бонуса')),
                ('bonus_reason', models.TextField(blank=True, help_text='Описание за что выплачен бонус', verbose_name='Причина бонуса')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Автоматически вычисляется: базовая сумма + бонус', max_digits=10, null=True, verbose_name='Итоговая сумма')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки о выплате', verbose_name='Примечания')),
                ('driver', models.ForeignKey(help_text='Водитель, которому производится выплата', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='drivers.driverprofile', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Выплата водителю',
                'verbose_name_plural': 'Выплаты водителям',
                'ordering': ['-payment_date'],
            },
        ),
    ]
