# Generated by Django 6.0 on 2025-12-20 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_created_at_alter_customer_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка о мягком удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Время когда запись была помечена как удаленная', null=True, verbose_name='Дата удаления')),
                ('source', models.CharField(choices=[('PHONE', 'Телефон'), ('EMAIL', 'Email'), ('WEBSITE', 'Сайт'), ('MESSENGER', 'Мессенджер')], help_text='Откуда поступила заявка', max_length=25, verbose_name='Источник заявки')),
                ('desired_trip_date', models.DateField(help_text='Дата когда клиент хочет совершить поездку', verbose_name='Желаемая дата поездки')),
                ('desired_departure_time', models.TimeField(help_text='Время отправления по желанию клиента', verbose_name='Желаемое время отправления')),
                ('arrival_location', models.CharField(help_text='Адрес или название пункта назначения', max_length=255, verbose_name='Место прибытия')),
                ('passenger_count', models.IntegerField(help_text='Сколько человек планируют поездку', verbose_name='Количество пассажиров')),
                ('luggage_description', models.TextField(blank=True, help_text='Информация о количестве и типе багажа', verbose_name='Описание багажа')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('CONFIRMED', 'Подтверждена'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='NEW', help_text='Текущий статус бронирования', max_length=50, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки и пожелания', verbose_name='Примечания')),
                ('customer', models.ForeignKey(help_text='Клиент, сделавший бронирование', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
