# Generated by Django 6.0 on 2026-01-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='desired_trip_location',
            field=models.CharField(default='', help_text='Адрес или название пункта отправления', max_length=255, verbose_name='Желаемое место отправления'),
        ),
    ]
