# Generated by Django 6.0 on 2025-12-20 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_alter_vehicle_category_alter_vehicle_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка о мягком удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Время когда запись была помечена как удаленная', null=True, verbose_name='Дата удаления')),
                ('expense_date', models.DateField(help_text='Дата совершения расхода', verbose_name='Дата расхода')),
                ('category', models.CharField(help_text='Тип расхода', max_length=50, verbose_name='Категория')),
                ('responsible_person', models.CharField(help_text='Кто произвел или согласовал расход', max_length=255, verbose_name='Ответственное лицо')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма расхода (в рублях)', max_digits=10, verbose_name='Сумма')),
                ('description', models.TextField(help_text='Подробное описание расхода', verbose_name='Описание')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Транспорт, связанный с расходом (если применимо)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-expense_date'],
            },
        ),
    ]
