# Generated by Django 6.0 on 2025-12-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание расхода', null=True, verbose_name='Описание'),
        ),
    ]
