# Generated by Django 6.0 on 2026-01-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='vehicle',
        ),
    ]
